from ed.jerarquicas.arbolBinario import ArbolBinario
from ed.jerarquicas.recorridos import *

if __name__ == '__main__':
    arbol = ArbolBinario()
    print("Altura del arbol vacio")
    print(arbol.altura())
    arbol.adicionar(4)
    print(arbol.altura())
    arbol.adicionar(5)
    print(arbol.altura())
    arbol.adicionar(6)
    arbol.adicionar(8)
    print(arbol.altura())
    print(arbol.buscar(6))
    print(arbol.__len__())
    #print("pre orden")
    preorden(arbol)
    print("pre orden str")
    print(cad_preorden(arbol))
    #print("in orden")
    inorden(arbol)
    print("in orden str")
    print(cad_inorden(arbol))
    #print("pos orden")
    postorden(arbol)
    print("pos orden str")
    print(cad_postorden(arbol))
    print("Hojas")
    print(arbol.hojas())
    print("Altura")
    print(arbol.altura())
    print("Nodos Internos")
    print(arbol.internos())