#!/usr/bin/env python
import sys
from ed.secuenciales.colaprioridad import ColaDePrioridad

if __name__ =='__main__':

    cola = ColaDePrioridad()

    print("str: "+ cola.__str__())
    print("len: "+str(len(cola)))
    print("frente: "+str(cola.frente()))
    print("nodo_cola: "+str(cola.nodo_cola))
    print("desencolar: "+str(cola.desencolar()))
    print("\n")

    print("encolar: "+str(cola.encolar(1,5)))
    print("str: "+ cola.__str__())
    print("len: "+str(len(cola)))
    print("frente: "+str(cola.frente()))
    print("nodo_cola: "+str(cola.nodo_cola.dato))
    print("\n")

    #print("desencolar: "+str(cola.desencolar()))

    print("encolar: "+str(cola.encolar(2,2)))
    print("str: "+ cola.__str__())
    print("len: "+str(len(cola)))
    print("frente: "+str(cola.frente()))
    print("nodo_cola: "+str(cola.nodo_cola.dato))
    print("\n")

    print("encolar: "+str(cola.encolar(3,3)))
    print("str: "+ cola.__str__())
    print("len: "+str(len(cola)))
    print("frente: "+str(cola.frente()))
    print("nodo_cola: "+str(cola.nodo_cola.dato))
    print("\n")

    print("encolar: "+str(cola.encolar("3",0)))
    print("\n")

    print("str: "+ cola.__str__())
    print("frente: "+str(cola.frente()))
    print("nodo_cola: "+str(cola.nodo_cola.dato))
    print("desencolar: "+str(cola.desencolar()))
    print("\n")

    print("frente: "+str(cola.frente()))  #DEBE IMPRIMIRME EL 2
    #print("nodo_cola: "+str(cola.nodo_cola.dato))
    print("str: "+str(cola))
    print("desencolar: "+str(cola.desencolar()))
    print("\n")
    print("frente: "+str(cola.frente()))
    #print("nodo_cola: "+str(cola.nodo_cola.dato))
    print("str: "+str(cola))
    print("desencolar: "+str(cola.desencolar()))
    print("\n")
    print("frente: "+str(cola.frente()))
    #print("nodo_cola: "+str(cola.nodo_cola.dato))
    print("str: "+str(cola))
    print("\n")

    print("encolar: "+str(cola.encolar(1,5)))
    print("str: "+str(cola))
    print("len: "+str(len(cola)))
    print("frente: "+str(cola.frente()))
    print("nodo_cola: "+str(cola.nodo_cola.dato))
    print("\n")
    print("encolar: "+str(cola.encolar(2,4)))
    print("str: "+str(cola))
    print("len: "+str(len(cola)))
    print("frente: "+str(cola.frente()))
    print("nodo_cola: "+str(cola.nodo_cola.dato))
    print("\n")
    print("encolar: "+str(cola.encolar("3",0)))
    print("str: "+str(cola))
    print("len: "+str(len(cola)))
    print("frente: "+str(cola.frente()))
    print("nodo_cola: "+str(cola.nodo_cola.dato))
    print("\n")
    print("encolar: "+str(cola.encolar(3,3)))
    print("str: "+str(cola))
    print("len: "+str(len(cola)))
    print("frente: "+str(cola.frente()))
    print("nodo_cola: "+str(cola.nodo_cola.dato))
    print("\n")
    print("encolar: "+str(cola.encolar(4,2)))
    print("str: "+str(cola))
    print("len: "+str(len(cola)))
    print("frente: "+str(cola.frente()))
    print("nodo_cola: "+str(cola.nodo_cola.dato))
    print("\n")
    print("encolar: "+str(cola.encolar("3",0)))
    print("str: "+str(cola))
    print("len: "+str(len(cola)))
    print("frente: "+str(cola.frente()))
    print("nodo_cola: "+str(cola.nodo_cola.dato))
    print("\n")

    print("encolar: "+str(cola.encolar(5,1)))
    print("str: "+str(cola))
    print("len: "+str(len(cola)))
    print("frente: "+str(cola.frente()))
    print("nodo_cola: "+str(cola.nodo_cola.dato))
    print("\n")
    print("encolar: "+str(cola.encolar(6,1)))
    print("str: "+str(cola))
    print("len: "+str(len(cola)))
    print("frente: "+str(cola.frente()))
    print("nodo_cola: "+str(cola.nodo_cola.dato))
    print("\n")
    print("encolar: "+str(cola.encolar("3",0)))
    print("str: "+str(cola))
    print("len: "+str(len(cola)))
    print("frente: "+str(cola.frente()))
    print("nodo_cola: "+str(cola.nodo_cola.dato))
    print("\n")
    print("encolar: "+str(cola.encolar(7,1)))
    print("str: "+str(cola))
    print("len: "+str(len(cola)))
    print("frente: "+str(cola.frente()))
    print("nodo_cola: "+str(cola.nodo_cola.dato))
    print("\n")
    print("encolar: "+str(cola.encolar(8,1)))
    print("str: "+str(cola))
    print("len: "+str(len(cola)))
    print("frente: "+str(cola.frente()))
    print("nodo_cola: "+str(cola.nodo_cola.dato))
    #print(cola.prior())
    print("\n")
    print("encolar: "+str(cola.encolar(20,1)))
    print("str: "+str(cola))
    print("len: "+str(len(cola)))
    print("frente: "+str(cola.frente()))
    print("nodo_cola: "+str(cola.nodo_cola.dato))
    #print(cola.prior())
    print("\n")
    print("encolar: "+str(cola.encolar(30,5)))
    print("str: "+str(cola))
    print("len: "+str(len(cola)))
    print("frente: "+str(cola.frente()))
    print("nodo_cola: "+str(cola.nodo_cola.dato))
    print("desencolar: "+str(cola.desencolar()))
    print("str: "+str(cola))
    #print(cola.prior())
    print("\n")

    
    ##### QUEDE AQUIIIIIIIII ######
    print("encolar: "+str(cola.encolar(20,10)))
    print("str: "+str(cola))
    #print("encolar: "+str(cola.encolar(20,100)))
    #print("str: "+str(cola))
    print("len: "+str(len(cola)))
    print("frente: "+str(cola.frente()))
    print("nodo_cola: "+str(cola.nodo_cola.dato))
    #print(cola.prior())
    print("\n")
    print("encolar: "+str(cola.encolar(10,8)))
    print("str: "+str(cola))
    print("len: "+str(len(cola)))
    print("frente: "+str(cola.frente()))
    print("nodo_cola: "+str(cola.nodo_cola.dato))
    #print(cola.prior())
    print("\n")
    print("encolar: "+str(cola.encolar(21,9)))
    print("str: "+str(cola))
    print("len: "+str(len(cola)))
    print("frente: "+str(cola.frente()))
    print("nodo_cola: "+str(cola.nodo_cola.dato))
    #print(cola.prior())
    print("\n")
    print("encolar: "+str(cola.encolar(8,9)))
    print("str: "+str(cola))
    print("len: "+str(len(cola)))
    print("frente: "+str(cola.frente()))
    print("nodo_cola: "+str(cola.nodo_cola.dato))
    #print(cola.prior())
    print("\n")
#[nodo_cola,20,8,21,10,30,1,2,3,4,20,8,frente]
print("desencolar: "+str(cola.desencolar()))
print("\n")
print("frente: "+str(cola.frente()))
#print("nodo_cola: "+str(cola.nodo_cola.dato))
print("str: "+str(cola))
print("desencolar: "+str(cola.desencolar()))
print("\n")
print("frente: "+str(cola.frente()))
#print("nodo_cola: "+str(cola.nodo_cola.dato))
print("str: "+str(cola))
print("desencolar: "+str(cola.desencolar()))
print("\n")
print("frente: "+str(cola.frente()))
#print("nodo_cola: "+str(cola.nodo_cola.dato))
print("str: "+str(cola))
#print(cola.prior())
print("len: "+str(len(cola)))
#print("frente: "+str(cola.frente()))
print("encolar: "+str(cola.encolar(29,1000)))
print("nodo_cola: "+str(cola.nodo_cola.dato))
print("str: "+str(cola))