#!/usr/bin/env python
#import sys
from ed.secuenciales.pila import Pila
from ed.secuenciales.nodo import NodoLSE

#MI TEST listaPila
if __name__ == "__main__":
    
    pila_numeros = Pila()
    print(pila_numeros.es_vacia())
    print(pila_numeros.__str__())
    print(pila_numeros.cima())
    print(pila_numeros.recorrer())
    print(pila_numeros.apilar(10))
    print(pila_numeros.__len__())
    print(pila_numeros.recorrer())
    print(pila_numeros.es_vacia())
    print(pila_numeros.recorrer())
    print(pila_numeros.desapilar())
    print(pila_numeros.recorrer())
    print(pila_numeros.es_vacia())
    print(pila_numeros.recorrer())
    print(pila_numeros.apilar(20))
    print(pila_numeros.__len__())
    print(pila_numeros.recorrer())
    print(pila_numeros.apilar(30))
    print(pila_numeros.apilar(40))
    print(pila_numeros.apilar(20))
    print(pila_numeros.apilar(50))
    print(pila_numeros.__str__())
    print(pila_numeros.__len__())
    print(pila_numeros.cima())
    print(pila_numeros.recorrer())
    print(pila_numeros.desapilar())
    print(pila_numeros.recorrer())
    print(pila_numeros.desapilar())
    print(pila_numeros.recorrer())
    print(pila_numeros.desapilar())
    print(pila_numeros.__len__())
    print(pila_numeros.recorrer())
    print(pila_numeros.desapilar())
    print(pila_numeros.recorrer())
    print(pila_numeros.desapilar())
    print(pila_numeros.cima())
    print(pila_numeros.desapilar())
    print(pila_numeros.es_vacia())
    print(pila_numeros.desapilar())
    print(pila_numeros.recorrer())
    print(pila_numeros.es_vacia())
    print(pila_numeros.cima())
    print(pila_numeros.desapilar())
    print(pila_numeros.recorrer())
    print(pila_numeros.__len__())
    print(pila_numeros.__str__())
