#!/usr/bin/env python
from ed.secuenciales.colaprioridad import Cola, NodoOrden, ListaOrdenada, ColaDePrioridad

if __name__ == "__main__":
    c = Cola()
    c.encolar("A")
    c.encolar("b")
    c.encolar("c")
    c.encolar("d")
    c.encolar("e")
    c.encolar("f")
    print(c, len(c))
    r = c.desencolar()
    while r is not None:
        print(r)
        r = c.desencolar()
    print("1.OK")
    print(c.__str__())
    print(c.desencolar())
    print(c.__str__())
    cp = ColaDePrioridad()
    print(cp.es_vacia())
    cp.encolar(1,"David")
    cp.encolar(3,"Victor")
    cp.encolar(2,"Juan")
    cp.encolar(2,"Dany")
    cp.encolar(3,"Sonia")
    cp.encolar(4,"Pablo")
    cp.encolar(5,"Jean")
    cp.encolar(2,"Adriana")
    cp.encolar(2,"Euglovio")
    cp.encolar(3,"Veronica")
    cp.encolar(5,"Josue")
    cp.encolar(4,"Cristiano")
    cp.encolar(7,"Lionel")
    print(len(cp))
    print(cp)
    print(cp.__str__())
    print(cp.frente())
    print(cp.desencolar())
    print(cp)
    while(cp.frente()):
        print(cp.desencolar())
    print(cp)
    print(cp.__str__())